name: deploy-container

on: 
  push:
    branches: 
      - master
      - main
    paths:
      - 'container/**'

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
      - run: npm install
      - run: npm run build

    