name: deploy-container

# this on is use to watch for events to run workflow and also use when the workflow run
# container/** specifies that when we have change in container then only run workflow
on: 
  push:
    branches: 
      - master
      - main
    paths:
      - 'container/**'

defaults:
  runs:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}